// Otomatik üretildi — karakter yaratma seçenek görselleri (Assets.xcassets).
enum BuilderImages {
    static func asset(_ category: String, _ value: String) -> String? {
        map["\(category)|\(value)"]
    }
    static let map: [String: String] = [
        "eyecolor|Amber": "b_eyecolor_Amber",
        "eyecolor|Blue": "b_eyecolor_Blue",
        "eyecolor|Brown": "b_eyecolor_Brown",
        "eyecolor|Emerald": "b_eyecolor_Emerald",
        "eyecolor|Gray": "b_eyecolor_Gray",
        "eyecolor|Green": "b_eyecolor_Green",
        "eyecolor|Hazel": "b_eyecolor_Hazel",
        "eyecolor|Steel Blue": "b_eyecolor_Steel_Blue",
        "eyecolor|Turquoise": "b_eyecolor_Turquoise",
        "eyecolor|Violet": "b_eyecolor_Violet",
        "age|18-21": "b_age_18_21",
        "age|22-27": "b_age_22_27",
        "age|28-35": "b_age_28_35",
        "age|36-42": "b_age_36_42",
        "age|43-52": "b_age_43_52",
        "age|53-65": "b_age_53_65",
        "age|65+": "b_age_75",
        "cat|Fictional": "b_cat_Fictional",
        "cat|Realistic": "b_cat_Realistic",
        "eth|African": "b_eth_African",
        "eth|East Asian": "b_eth_East_Asian",
        "eth|European": "b_eth_European",
        "eth|Latina": "b_eth_Latina",
        "eth|Mediterranean": "b_eth_Mediterranean",
        "eth|Middle Eastern": "b_eth_Middle_Eastern",
        "eth|Mixed": "b_eth_Mixed",
        "eth|North African": "b_eth_North_African",
        "eth|Scandinavian": "b_eth_Scandinavian",
        "eth|Slavic": "b_eth_Slavic",
        "eth|South Asian": "b_eth_South_Asian",
        "eth|Southeast Asian": "b_eth_Southeast_Asian",
        "haircolor|Auburn": "b_haircolor_Auburn",
        "haircolor|Black": "b_haircolor_Black",
        "haircolor|Blonde": "b_haircolor_Blonde",
        "haircolor|Blue": "b_haircolor_Blue",
        "haircolor|Brown": "b_haircolor_Brown",
        "haircolor|Copper": "b_haircolor_Copper",
        "haircolor|Pink": "b_haircolor_Pink",
        "haircolor|Purple": "b_haircolor_Purple",
        "haircolor|Red": "b_haircolor_Red",
        "haircolor|Silver": "b_haircolor_Silver",
        "hair|Bob": "b_hair_Bob",
        "hair|Braided": "b_hair_Braided",
        "hair|Bun": "b_hair_Bun",
        "hair|Curly": "b_hair_Curly",
        "hair|Long Layers": "b_hair_Long_Layers",
        "hair|Pixie": "b_hair_Pixie",
        "hair|Ponytail": "b_hair_Ponytail",
        "hair|Straight": "b_hair_Straight",
        "hair|Undercut": "b_hair_Undercut",
        "hair|Wavy": "b_hair_Wavy",
        "prof|Artist": "b_prof_Artist",
        "prof|Athlete": "b_prof_Athlete",
        "prof|Chef": "b_prof_Chef",
        "prof|Doctor": "b_prof_Doctor",
        "prof|Gamer": "b_prof_Gamer",
        "prof|Model": "b_prof_Model",
        "prof|Musician": "b_prof_Musician",
        "prof|Photographer": "b_prof_Photographer",
        "prof|Scientist": "b_prof_Scientist",
        "prof|Student": "b_prof_Student",
        "prof|Warrior": "b_prof_Warrior",
        "prof|Writer": "b_prof_Writer",
        "bodytype|Slim": "b_bodytype_Slim",
        "bodytype|Athletic": "b_bodytype_Athletic",
        "bodytype|Curvy": "b_bodytype_Curvy",
        "bodytype|Average": "b_bodytype_Average",
        "bodytype|Voluptuous": "b_bodytype_Voluptuous",
        "bodytype|Plus Size": "b_bodytype_Plus_Size",
        "skin|Caramel": "b_skin_Caramel",
        "skin|Deep": "b_skin_Deep",
        "skin|Fair": "b_skin_Fair",
        "skin|Golden": "b_skin_Golden",
        "skin|Porcelain": "b_skin_Porcelain",
        "skin|Tan": "b_skin_Tan",
        "vibe|Elegant": "b_vibe_Elegant",
        "vibe|Energetic": "b_vibe_Energetic",
        "vibe|Mysterious": "b_vibe_Mysterious",
        "vibe|Sweet": "b_vibe_Sweet",
    ]
}
