//
//  HelpSupportView.swift
//  "Yardım & Destek" — Profil sekmesindeki minimal statik FAQ + iletişim ekranı.
//

import SwiftUI

struct HelpSupportView: View {
    @Environment(\.dismiss) private var dismiss

    private let supportEmail = "destek@wecan.app"

    private let faqs: [(String, String)] = [
        (String(localized: "Are the characters real?"),
         String(localized: "No, all characters are fictional personalities generated by AI.")),
        (String(localized: "Where is my chat history stored?"),
         String(localized: "Your messages are stored on your device, not on the server.")),
        (String(localized: "How do I delete my character?"),
         String(localized: "You can use the 'Clear Chat' option from the gear menu on the chat screen.")),
    ]

    var body: some View {
        NavigationStack {
            ZStack {
                AppColor.bg.ignoresSafeArea()
                ScrollView {
                    VStack(alignment: .leading, spacing: 20) {
                        contactCard
                        faqSection
                    }
                    .padding(20)
                }
            }
            .navigationTitle("Help & Support")
            .navigationBarTitleDisplayMode(.inline)
            .toolbarBackground(AppColor.bg, for: .navigationBar)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Close") { dismiss() }
                }
            }
        }
        .preferredColorScheme(.dark)
    }

    private var contactCard: some View {
        Link(destination: URL(string: "mailto:\(supportEmail)")!) {
            HStack(spacing: 14) {
                Image(systemName: "envelope.fill")
                    .font(.system(size: 16))
                    .foregroundStyle(AppColor.pink)
                    .frame(width: 36, height: 36)
                    .background(AppColor.pink.opacity(0.15), in: Circle())
                VStack(alignment: .leading, spacing: 2) {
                    Text("Send us an email")
                        .font(.system(size: 15, weight: .semibold))
                        .foregroundStyle(.white)
                    Text(supportEmail)
                        .font(.system(size: 13, weight: .medium))
                        .foregroundStyle(.white.opacity(0.6))
                }
                Spacer()
                Image(systemName: "chevron.right")
                    .font(.system(size: 13, weight: .semibold))
                    .foregroundStyle(.white.opacity(0.4))
            }
            .padding(14)
            .background(Color.white.opacity(0.05), in: RoundedRectangle(cornerRadius: 16))
        }
        .buttonStyle(.plain)
    }

    private var faqSection: some View {
        VStack(alignment: .leading, spacing: 14) {
            Text("FREQUENTLY ASKED QUESTIONS")
                .font(.system(size: 12, weight: .bold))
                .tracking(0.5)
                .foregroundStyle(.white.opacity(0.5))
            ForEach(faqs, id: \.0) { question, answer in
                VStack(alignment: .leading, spacing: 4) {
                    Text(question)
                        .font(.system(size: 14, weight: .semibold))
                        .foregroundStyle(.white)
                    Text(answer)
                        .font(.system(size: 13, weight: .regular))
                        .foregroundStyle(.white.opacity(0.65))
                }
                .padding(14)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Color.white.opacity(0.05), in: RoundedRectangle(cornerRadius: 14))
            }
        }
    }
}

#Preview {
    HelpSupportView()
}
